- name: Instalar Java 17 no servidor
  hosts: aws-host
  become: yes  # executa com sudo
  tasks:
    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
